### ISSUE TITLE
Trouble Saving Code - No Disk Space

### ISSUE THREAD

**Issue by dhilgaertner** [scraperwiki/code-scraper-in-browser-tool#135]
I get the following error each time I try to use 'code-in-the-browser'.  

    Trouble saving code! mv: cannot move ‘code/scraper.new.12961’ to ‘code/scraper’: No space left on device.

Related errors also happen when trying to run the code.  Basically it appears the app is completely inoperable till the 'disk space' issue is resolved.

**Comment by StevenMaude** [comment]
Assuming this is an old issue, and due to a temporary outage. Please create a new issue if the problem persists.
