### ISSUE TITLE
'This dataset is empty' error on new scrapers

### ISSUE THREAD

**Issue by emanuelfeld** [scraperwiki/code-scraper-in-browser-tool#140]
Just wrote a new scraper. After running it, I see 'This dataset is empty' when I click to view in a table. To make sure this isn't just a fault of my code, I copied the scraper script for a previously written (and still running) scraperwiki scraper and I get the same message.

**Comment by StevenMaude** [comment]
Doesn't seem to be reproducible; maybe a transient problem?

**Comment by emanuelfeld** [comment]
Honestly, I don't even remember writing this issue.

**Comment by StevenMaude** [comment]
No problem :smile:
