### ISSUE TITLE
scraperwiki python library not available in python 3

### ISSUE THREAD

**Issue by wdwhy** [scraperwiki/code-scraper-in-browser-tool#145]
When using python 3 in the in-browser tool by changing the hashbang to `#!/usr/bin/env python3`, the import fails with error:

`ImportError: No module named 'scraperwiki'`

**Comment by StevenMaude** [comment]
Thanks for reporting and sorry for the delay in replying.

This might have been an issue back in April, can't currently replicate so think it's been installed since. (tried in new dataset just now). Please feel free to raise again if it continues to be a problem.
