### ISSUE TITLE
Change description so says better what it does

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/code-scraper-in-browser-tool#72]
'Use Ruby, PHP or Perl [etc] to scrape data from web pages' 
rather than  'Just like you used to on ScraperWiki Classic'.

What about those that didn't know/use the Classic version?

Original bug: https://github.com/scraperwiki/custard/issues/217

**Comment by StevenMaude** [comment]
Think this was changed; closing. (It's "Write scripts in Python and other languages" now.)
